version: '3.4'

services:
  postgres:
    image: postgres:latest
    container_name: db-polyglot
    environment:
      POSTGRES_DB: polyglotpersistence
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    restart: always
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:latest
    container_name: db-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: 123456
    restart: always
    ports:
      - "27017:27017"
